### PR TITLE
Added 'ee4 list' command

### LINKED ISSUE #32: Add list command
Add `ee4 list` command

### PR DESCRIPTION
**Pull request by dharmin**
Fix #32

### CODE REVIEW

**Comment by mbtamuli** [comment]
Escape characters showing up.
```
> ee4 list
\e[1;31mNo sites have been created.
-----
> ee4 list

\e[1;32mList of Sites:

\e[1;38;5;25mexample.com
notasite
simplefolder
zzz.test
```

**Comment by mbtamuli** [comment]
@dharmin Currently it is displaying even text files and random directories in the webroot.
Use `find` to only filter only (1)_directories_ which (2)contain a _docker-compose.yml_ file.

**Comment by mbtamuli** [comment]
At the current state, it correctly lists sites only, but output is wrong.
```
> ls -al
total 0
drwxr-xr-x  6 rtc 192 Feb 13 12:40 .
drwxr-xr-x 14 rtc 448 Feb 13 12:53 ..
drwxr-xr-x  7 rtc 224 Feb 13 12:38 example.com
drwxr-xr-x  2 rtc  64 Feb 13 12:39 notasite
drwxr-xr-x  2 rtc  64 Feb 13 12:40 test
drwxr-xr-x  7 rtc 224 Feb 13 12:40 zzz.test
> ee4 list
List of Sites:

examplecom
zzztest
```
It removes the period.

**Comment by dharmin** [comment]
Fixed. Used cut command instead of tr to fix it

**Comment by mbtamuli** [comment]
LGTM

**Pull request merged**
